### ISSUE TITLE
Live Twitter example would be great

### ISSUE THREAD

**Issue by todb-r7** [gmatuz/inthewilddb#2]
The most interesting part, to me, about inthewild.io is the Twitter-based submission. However, there don't seem to be any! It would be swell if there was just one to look at (and it's implied it exists in the screencap on the site).

IOW, when https://twitter.com/search?lang=en&q=(to%3Ainthewildio)&src=typed_query returns any result, this issue is resolved.

**Comment by donchev7** [comment]
Hi, yeah you are right. The reason the query didn't return anything was just that there weren't any tweets @us.

The screencap on the site hopefully conveys the message that you can contribute by tweeting at us. It's more a call to action of how easy contribution can be.

I just created a test tweet to verify your query and it shows up. Getting the community to help contribute is another story.

**Comment by gmatuz** [comment]
good point added a complete example here, thanks for the nudge @todb-r7 !
https://twitter.com/4lreadytekken/status/1463474094947581955

**Comment by gmatuz** [comment]
Added the twitter submission examples
